### ISSUE TITLE
Milti-platform images buildx

### ISSUE THREAD

**Issue by D1ver** [yc-actions/yc-sls-container-deploy#454]
Если собирать образ без явного задания платформы, то выпадет ошибка, даже не стартуя.
Может из-за того, что собираю образы на Маке из под Mac OS.

Поддержка Облака рекомендовала явно задавать платформу.
Вот здесь пример: https://docs.docker.com/build/building/multi-platform/

Поэтому можно добавить вместо:
`docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .`

Явную сборку:
`docker buildx build --platform linux/amd64 -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .`

**Comment by nikolaymatrosov** [comment]
Да, на вашем маке правильно собирать образы, как вам рекомендовала поддержка. А экшен тут при чем?
