### ISSUE TITLE
Невалидная версия экшена в ридми

### ISSUE THREAD

**Issue by r34son** [yc-actions/yc-sls-container-deploy#505]
Привет! Не мог бы ты поправить в ридми версию экшена 
 `uses: yc-actions/yc-cr-login@v2` ->  `uses: yc-actions/yc-cr-login@v1`

**Comment by nikolaymatrosov** [comment]
Такой версии нет

**Comment by r34son** [comment]
Как раз второй нет, а она указана в ридми
