### ISSUE TITLE
[Feature Request] Возможность создавать контейнеры публичными

### ISSUE THREAD

**Issue by r34son** [yc-actions/yc-sls-container-deploy#506]
Хотелось бы иметь возможность создавать контейнеры публичными.
Можно отсюда взять реализацию https://github.com/r34son/profile/blob/master/.github/actions/yc-sls-container-public/src/index.ts

**Comment by nikolaymatrosov** [comment]
Вы можете оформить это как pull request. Это сильно ускорит появление этой фичи.

**Comment by nikolaymatrosov** [comment]
Вам поможет эта инструкция. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
