### ISSUE TITLE
Роли необходимые для аккаунта

### ISSUE THREAD

**Issue by mimpushkarev** [yc-actions/yc-sls-container-deploy#535]
При указании секретов lockbox при выполнении экшена, падает с ошибкой (если указывать только те роли, что указаны в readme)

```
Error: ClientError: /yandex.cloud.serverless.containers.v1.ContainerService/DeployRevision PERMISSION_DENIED: Permission denied
Error: /yandex.cloud.serverless.containers.v1.ContainerService/DeployRevision PERMISSION_DENIED: Permission denied
```

Пробовал повесить:

- lockbox.editor
- lockbox.payloadViewer
- lockbox.viewer

Ни один из вариантов, проблему не порешал

Workaround: Выдавать ```editor``` аккаунту, но это не безопасно

**Comment by nikolaymatrosov** [comment]
Да, если у вас просто секрет, то должно быть достаточно роли `lockbox.payloadViewer`.
Если он зашифрован ключом KMS, то еще понадобится роль `kms.keys.decrypter`.
