### ISSUE TITLE
Права доступа для указания revision-network-id

### ISSUE THREAD

**Issue by pyatnitsev** [yc-actions/yc-sls-container-deploy#564]
Добрый день!

Указываю идентификатор сети в revision-network-id, тогда получаю

Error: ClientError: /yandex.cloud.serverless.containers.v1.ContainerService/DeployRevision INVALID_ARGUMENT: VPC Network <network_id> not found or permission denied

Сервисный аккаунт имеет права vpc.admin на уровне облака. 

Что нужно дать дополнительно?

**Comment by nikolaymatrosov** [comment]
Какой именно сервисный аккаунт имеет эти права? От которого выполняется action или тот с которым деплоится ревизия?

**Comment by pyatnitsev** [comment]
В моем случае это один и тот же аккаунт

**Comment by nikolaymatrosov** [comment]
Роли должно хватать. Обратитесь в саппорт облака. Возможно ошибка в том, что вы исчерпали квоту сетей. https://cloud.yandex.ru/ru/docs/serverless-containers/concepts/limits#serverless-containers-quotas

**Comment by pyatnitsev** [comment]
Ok. Сделаю тикет, 
с квотами только что разобрались - их использовать можно. Я могу из панели задать сеть.

Спасибо!
